### ISSUE TITLE
Duidelijk e-mail bij aanmelding nieuw lid

### ISSUE THREAD

**Issue by AmberPater** [lukovdm/bf2-www#176]
Als een nieuw lid zich aanmeldt via de website meteen een e-mail sturen waarin staat dat ze nog niet direct lid zijn, maar dit eerst goedgekeurd moet worden door de secretaris, wat uiterlijk twee weken zal duren en dat ze na het besluit een e-mail ontvangen over de toelating.

**Comment by Elian8or** [comment]
Nienke heeft het gedaan, template word nog goed bekeken door onze lieve seccie
