### ISSUE TITLE
Apply design to members app 

### ISSUE THREAD

**Issue by NienkePienke01** [lukovdm/bf2-www#26]
pages that need design: 
- become a member

**Comment by lukovdm** [comment]
Here are current designs:
![become_a_member](https://user-images.githubusercontent.com/3864622/111366927-715af400-8694-11eb-94fb-219a6e69ca39.png)

**Comment by Elian8or** [comment]
![image](https://user-images.githubusercontent.com/80771700/112135014-9c31d480-8bcd-11eb-85af-6a7d5f8eb0c3.png)

**Comment by Elian8or** [comment]
Kleine update, ingevulde versie (zwart ipv grijs), met sterretjes bij verplichte dingen (geen idee wat er verplicht is btw). En wat hij weergeeft als hij iets mist. 
![image](https://user-images.githubusercontent.com/80771700/112748117-1392aa00-8fba-11eb-9be2-ceb8268d5467.png)

**Comment by Elian8or** [comment]
Willen we ook een privacyverklaring erin zetten, waar ze actief mee eens mee moeten zijn?

**Comment by lukovdm** [comment]
Yes, dus daar een vinkje voor en er kan iets fouts worden ingevuld en dan moet dat er bij komen te staan
